{
  "formatVersion": "1.1",
  "component": {
    "group": "com.milodygames.sdk",
    "module": "test",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-1.0.0.aar",
          "url": "test-1.0.0.aar",
          "size": 296681,
          "sha512": "36a0f87a8588978084009e9c75b6095d58e44b5378d49f92ec6cc220e4686c087c55b25efe83a56e3eea671fe4ecf1fe7462d0d44d70c60f67400114f4012c83",
          "sha256": "dfca5dab132535661238d3112a43ed120a06da0d5b3725958e1c05d7820864d8",
          "sha1": "9330880d6467f2df1597d6eb2e51d2975e750cc2",
          "md5": "0c3531cc0247ec9ec19c69b59840f8d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-1.0.0.aar",
          "url": "test-1.0.0.aar",
          "size": 296681,
          "sha512": "36a0f87a8588978084009e9c75b6095d58e44b5378d49f92ec6cc220e4686c087c55b25efe83a56e3eea671fe4ecf1fe7462d0d44d70c60f67400114f4012c83",
          "sha256": "dfca5dab132535661238d3112a43ed120a06da0d5b3725958e1c05d7820864d8",
          "sha1": "9330880d6467f2df1597d6eb2e51d2975e750cc2",
          "md5": "0c3531cc0247ec9ec19c69b59840f8d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-1.0.0-sources.jar",
          "url": "test-1.0.0-sources.jar",
          "size": 3563,
          "sha512": "3fb3ac67ddde1b9038643bf4c49101de454cd38599652245b3dd6c99a7ef38575abedef2c1895ad37a6f1b6d0f6930ed9da7ec878cb3296ef2cf448ee08b8c9f",
          "sha256": "b9e1b99f229cc00cf71ea4e415c212436d81c6adecc6aad76fbbcf0e4d1a0d68",
          "sha1": "dbbfa00b02fe991a93fc7a3bfc82e1943b4ebbea",
          "md5": "e90c865cd96afebff87c1703b823023c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-1.0.0-javadoc.jar",
          "url": "test-1.0.0-javadoc.jar",
          "size": 269747,
          "sha512": "d2f1b936c5b7c37f4a245ff19acf8dea577a7d0c664b24e32666af950ae52859486e82aa50eb1a4ac59ebcf1714a0eaa66a215eb2ee54f719c2e8de6fd74b4d6",
          "sha256": "b01d28f41e50ca52df4db087fb11d39a32f1060584aa82aa9d75c7b2409e2dbd",
          "sha1": "e4ddf3c3bafa2f01bbab98904d7ed95a8ce87ad4",
          "md5": "036f7829ba5905db2b389a7b44a31f22"
        }
      ]
    }
  ]
}
